## Truth has left the table?

Adrian Mackenzie, 16 October 2015

The title actually comes from Michel Foucault's _The Order of Things: An Archaeology of the Human Sciences_ [@Foucault_1992]. This book unexpectedly resonates with some transformations in contemporary sciences of order.  A possible subtitle for this paper might be: 'transformations in life, labour and language associated with data.' What I offer here is just the outline of an argument that I have developed at greater length elsewhere. I say 'offer' because I'm quite uncertain of how this argument intersects with an ethnographic sensibility and approach to knowledge-making. I'm hoping intersections can be developed in discussion. While I'm relying on Foucault here quite a lot, I'm using his argument about transformations in order as a well-known reference point, rather than saying we must see what happens with big data in Foucaultean terms. 

The broad argument is something like this:

1. It seems that data increasingly takes highly composite or complex forms today. That can be exemplified in many different ways, but the key point is that 'big data' seems to have a complex composition. Despite this complexity, tables and tabulations of data remain absolutely central in data practice. This can be exemplified in various ways, but names like Google 'BigTable' or the many references to 'dataframes' (see R and Python) might be a starting point, or a brief survey of database architectures and their continued reliance on table components such as rows, columns and indexes suggest that tables remain in force amidst all the voluminous streams. It may be that Big Data could be approached as Big Table. And then the question would be: what are we to make of the persistence or expansion of the table as the basic form of data? Is there anything at stake in tabulation or the grid?

2. If we follow Foucault's argument in _The Order of Things_, tables shouldn't matter anymore. Truth escaped from the table somewhere around the beginning of the 19th century. What replaced the table? In Foucault's own diagrams, a set of diagonal relations supplanted the taxonomic, measural and ranking operations of the classical table. In the actual talk, I'll show some examples of this, including Foucault's own drawings. Along these diagonal lines, what mattered was not the analytics of difference and identity (carried through taxonomic subdivision and algebraically manipulated measurements), but an 'area of made up ... of internal relations between elements whose totality performs a function' (236). 'Function' figures very heavily in the re-organised knowledge area Foucault describes. (On some pages, Foucault uses 'function' ten times.) In life, in labour and language, functions operate as connective tissue. For instance, functions become essential to living things not as a way of describing differences but as their operational mode of existence. 'Reproduction is essential function of living things,' for instance. 

3. What happened to tables when relations and functions became the epistemic anchor points? The area of table, composed of cells, could not accommodate the sub-divisions needed to pursue these relations. Neither classification nor any controlled nomenclature could accommodate the plurality of relations. In a sense, the table could not accommodate new depths or the 'obscure verticality,' which is basically time (historical/evolutionary/temporality of experience): 

    'In order to discover the fundamental groups into which natural beings can be divided, it has become necessary to explore in depth the space that lies between their superficial organs and their most concealed ones, and between these latter and the broad functions that they perform.' (249)

4. If this obscure verticality still operates, what mean it mean for the multiplying, expanding area of knowledge we call 'Big data'? If Big Data is a Big Table, what does that mean for truth, for empiricity, for positivity, for referentiality or the contemporary episteme? Many other questions might proliferate here too, but my examples will touch on some of the proximities, coalescences and syntheses that such tables summon into existence. They all edge around the following framing: the expansion of contemporary tables might represent a departure from the functional depth, or it might represent a deepening of that functional depth. Or perhaps BigTable *re-surfaces depth.*  Whether the Big Table makes things more shallow or more deep matters less than the question of what happens to central binaries of living vs non-living, the sayable and the visible (see [@Foucault_1972].

5. If the central binaries -- living vs. non-living, the sayable vs. the visible -- shift, then we have to reckon with powerful realignments in the diagrams of power that configure fields of knowledge, institution, and subject positions. For reasons of time, I will forego exploration of these matters in the paper. I will, however, offer some brief description of Big Table operations that might help us think about the re-surfacing of depth. This will include:
    
    - _The common vector space_ as high dimensional meta-table. Something happened to mathesis when algebra encountered matrices (tables!) of numbers and operations. A common vector space took shape whose dimensionality became potentially infinite. Depth was still there, but traversable and topologically re-configurable through algebraic operations. 
    
    - *The decision surface:* R.A. Fisher's linear discriminant analysis, a key machine learning techniques, developed in mid-1930s as a way to classify taxonomically on measurement data. This cuts diagonally across the Classical table (since measurement and taxonomy act orthogonally there) but also surfaces evolutionary or population differences that should not be visible in either the horizontality or verticality of the table

    - *Inceptionism:*  Deep Learning in the form of recurrent convolutional neural nets has recently moved from an analytic to a generative mode. It makes statements and visible forms in the world (google 'inceptionism') on the basis of vast tabulations of existing documents or images, all of which find themselves re-mapped into a high-dimensional vector space. 

6. I tend to think that the tremendously energetic efforts to classify, order and rank, and sometimes to find pattern, pushes the table backwards through Foucault's analysis, re-surfacing the depths of life-labour-language, diagonalising the mathesis-taxonomia of the Classical table,  so that it might well end up in the Renaissance, where tables could accommodate all many of beings, and generated a stream of potential resonances, similarities and affinities. As a science/technology of order, Big Data would capitalise on the wonder of those affinities, but what else would it happen in that capitalisation? If biopower predicated force in the depths of the life-labour-language nexus, what predicates itself in the re-surfacing of the table? 

## References


The argument will run as follows:

1. MF said 'truth has left the table' in describing the transformation between the Classical sciences of order and the 'contemporary/human' sciences of life, labour and language. The transformation occurs sometime around the end of the 18th century, and ushers in new forms of knowing, new empiricities and positivities, new referentials, and in general a vast re-distribution and re-organisation of what counts as knowledges. Social sciences and various humanities, knowledges concerning labour, markets and value, sense of history, culture, human groupings, kinship all shift in profound ways. Foucault develops many different implications of this, but famously they include the figure of the human, about to be washed away in the sand. Perhaps more usefully, he describes the subterranean passages running between seemingly different objects such as money, dialects and organisms. I'm hoping this argument is familiar: it forms the background to much of  Foucault's later work and to the massive literature on biopower, biopolitics and neoliberal governmentality. For my purposes, I want to highlight simply _the table_.

2. The table organises the Classical (post-Renaissance) science of order in several ways. It departs from Renaissance (and earlier) tabulations of knowledge thatworked on analogies and similitudes. It replaces the proliferating multiplicities of analogy and similarities with two orthogonal movements, one dealing with simple natures and the other with complex natures.

    a. Algebra or _mathesis_ deals with simple natures using measurements and order. Importantly measurement and order -- as in succession or ranking -- are irreducible to each other
    
    b. Taxonomic order spread differences laterally, widening the table to include sub-columns and sub-divisions. A brief glance at a page of Linnaeus (natural historian of the 17th century) shows this. Taxonomy, whether in natural history, in history of peoples or administration, addressed complex nature or composite beings; entities whose composition could be analysed and organised hierarchically (taxa-genera-species, etc.)

Foucault writes 'the fundamental area of the ordered table was established between the calculation of equalities and the genesis of representations' (81). The 'fundamental area of the table' brought calculation and representation, measurement and differences together without any possibility of reducing one to the other. The world of living things, the grammars of languages, the accounting of exchange, money and goods is not mathematised in the table, but they do come into relation.

3. All of this changes sometime early in the 19th century. The table 

