
## Mon  3 Oct 12:00:53 BST 2016

- looking at O'Reilly AI conference (http://conferences.oreilly.com/artificial-intelligence/ai-deep-learning-bots-ny/public/schedule/grid/public/2016-09-26?view=list)[http://conferences.oreilly.com/artificial-intelligence/ai-deep-learning-bots-ny/public/schedule/grid/public/2016-09-26?view=list] -- has a major list of how ai is being operationalised as part of infrastructure. Could go through this  and analyse what is happening .. downloaded the days programs ast data/2016-09-26?view=list and data/2016-09-27?view=list
- range of concerns covered here -- from platform to work, from democraticisation to human culture, etc. are symptomatic ... 
- also companies like https://backchannel.com/you-too-can-become-a-machine-learning-rock-star-no-phd-necessary-107a1624d96b#.55l4nloxi will be part of this: Bonsai, a bit like OpenAI, and PredictionIO, and PredictionAPI, ... 

## Wed 15 Mar 2017 09:30:59 GMT
- I'm still interested in Kaggle competitions -- could perhaps learn a lot from looking at the differences between those more closely. e.g. https://www.kaggle.com/c/dstl-satellite-imagery-feature-detection could be worth a look

## Wed 30 Aug 2017 16:48:26 BST
- imagenet is a really obvious candidate to talk about the implications of my argument https://qz.com/1034972/the-data-that-changed-the-direction-of-ai-research-and-possibly-the-world/  

## Tue 14 Nov 2017 13:24:37 GMT
- still also have the idea of the model of machine learning and how it might include all the subjects, enunciations, operations and functions in as weighted variables, etc. -- this might be a figure that helps communicate with machine learners. 

## Sat 18 Nov 2017 15:44:12 GMT
- didn't realise that anomaly and outlier detection mainly use machine learning; another possible area to write about; cf what that paper by Tobias Blanke and Aradau discusses in Paris

## Thu 07 Jun 2018 14:11:08 BST
- Zuberi on statistics and the construction of race: how is that being re-done today in machine learning? 

## Thu 11 Oct 2018 09:45:30 AEDT
- xgboost as a classic data science library -- would be useful to track its growth on  Github and the like

```{r xgb}
library(xgboost)
# load data
data(agaricus.train, package = 'xgboost')
data(agaricus.test, package = 'xgboost')
train <- agaricus.train
test <- agaricus.test
# fit model
bst <- xgboost(data = train$data, label = train$label, max_depth = 2, eta = 1, nrounds = 2,
               nthread = 2, objective = "binary:logistic")
importance  <- xgb.importance(feature_names = colnames(train), model=bst)
xgb.plot.importance(importance_matrix = importance)
# predict
pred <- predict(bst, test$data)
help.start()
```


## Tue 13 Nov 2018 14:15:49 AEDT
- discussing the many fairness kits for  machine learning with Anna -- what are they doing? Is that going to work? To do what?
- this might be an occasion to do some ontography [@Lynch_2013]:

>conduct empirical studies of specific instances in which ontological questions are ‘in actuality decided through specific, historical, cultural, technological, scientific interventions’, and then, if one so chooses, to go further with experimental interventions.
- that's actually Marres

## Tue 04 Dec 2018 11:01:11 AEDT
- AINow conference program https://ainowinstitute.org/ainow-program-2018.html has talks worth listening too 

## Mon 01 Apr 2019 15:29:45 AEDT
- current hot research problems in  machine learning - see https://www.quora.com/What-are-the-current-research-problems-in-machine-learning-right-now
1) Why deep learning works (a biggie)
2) Theoretical guarantees of topological data analysis (stability, for instance)
3) Sueprlearning and other meta-learning strategies
4) Bayesian-based algorithms, particularly for deep learning and generalizable AI
5) Quantum machine learning and how to convert algorithms to quantum systems (https://www.slideshare.net/Colle...)
6) Hardware-interfacing algorithms that can leverage things like GPUs (kind of like XGBoost)
7) Replacing linear algebra and numerical matrices with the tools of numerical algebraic geometry

Many, many more!

This reminds me a bit of the Test of Time talk given at NIPS 2017 about gradient descent; see notes for Susan Halford talk, late March 2019; green small notebook 

## Tue 02 Apr 2019 17:07:30 AEDT
- DFW call for international teams -- people in Germany:
    - Gerlitz
    - Hinterwaldner
    - Gramelsberger
- the call is here: https://www.bmbf.de/foerderungen/bekanntmachung-2377.html#header
- call also involve Media of Calculation Research Group at Amsterdam?

## Sat 06 Apr 2019 09:05:30 AEDT
- reading SciAm 2017(?) about prediction for mental health and education; predictive education? How does prediction fit with future more generally? Cf Halford talk on futures ...  
- many articles and systems using dyslexia; and speaking of a post-dyslexic world because the time of reading has gone. See Gabrieli's work in Science and also the Diffusion Tensor Imaging. Fascinating that the prediction & humanitarian article at https://www.sciencedirect.com/science/article/pii/S0896627314009672 actually goes through the studies and lists the model used in terms of whether it is really predictive or not. I've not seen this criteria of prediction used before.  
- 
