
## Fri 09 Jun 2017 10:20:14 BST
- ideas for the Governing Prediction event in Paris september:
     - I don't want to do a new paper, so the question is: what do I have in the book that I can use to talk about governance;
     - Could just go with a basic Foucaultean argument about the observer and its transformation in ml.  That might mean using a bit of the Crary stuff, or my own account of what governs the production of statements. 
    - possible topics include the fake news stuff? Would that be enough? Or something more focused on a particular domain? Is there some dataset that is particularly problematic around governance that I could focus on. 
        - maybe all datasets are problematic in that they are tables. A new mode of inhabiting the table. Isn't that my key argument? How would I exemplify that? By working through an example of what happens to an image in a CNN? What happens to faces, for instance, in the predictive classificatory orderings?  
     - what about GDELT as a system? How does that fit into governance?  
     - or what about the Google global fishing example? and how that compares with what the NSA does? Or the Facebook case? Or the role of Cambridge Analytics in elections? 
     - could make my life a bit easier by using the Planetary Settlement Project and the ways in which governance (biopolitical, economic, etc.) switches around to predictive operationality; maybe in all of these, the question is bringing governance to bear on that which previously had not been governed. The multiplicity. 
     - But I don't do governance. what is governance? How does it related to governmentality?  could follow Barry who sees tech as an orientation to the political present. That could be a useful tension: predictive operationality and the invention of political institutions  
     - possible titles: predictive operationality and the invention of political institutions
     - to contextualise: Jasanoff's work on policy/government/science? Is science a key figure for me?
     - a key question (following Lynch on epistoics) -- how does something get described as a prediction? And what about all the things that are predictive, but not named as such? This is hardly ever talked about ...   

## Fri 16 Jun 2017 12:39:47 BST
- I don't what governance is. What is it? Is it the same as governing? Also, where does governmentality fit? 
- downloaded 2500 records on governmentality and saved in support/gov.tsv 
- working on titles more

## Mon 19 Jun 2017 15:26:08 BST
- need to send the title, but don't want to do the new work.
- listened to a podcast - twice -- interview with Andrew Hwang, global policy lead for AI at google. He doesn't seem to be able to talk about policy, but mentioned some useful examples and leads on it
    - UK and Obama US reports on AI
    - need to look at very localized, mundane transformations
    - understanding of policy as the link between tech and social change; 
    - has some stuff on fairness and why its not an interesting topic
    - also on explainability and its requirements; 
    - books to look at: Ian Goodfellow and the Cybersyn book 
- DONE: check library for these - DONE
- could just talk about the challenge of explainability based on 'vectorisation and its consequences' 
- there's quite a lot happening in terms of fairness(?). Maybe

## Tue 20 Jun 2017 15:55:45 BST
- been thinking that for me the arguments about fairness, discrimination, explainability all come too late. If governance is always part of the situation, and governmentality involves forms of observation, what happens with the change in observer?  
- possible titles:
    - Techniques of the Predictor;
    - Vectorising things out: prediction and its consequences

-   looking at literature -- key references cited around governmentality are Dean 1999, Foucault, 1991, Rose 1997, Foucault 2007, and Beck as well as Andrew Barry 1996


## Fri 23 Jun 2017 14:08:42 BST
- still wrestling a bit with writing this abstract -- I don't want to commit myself to new work. But did look at references that are most cited: Foucault, 2007 can be found at http://lib.myilibrary.com.ezproxy.lancs.ac.uk/Open.aspx?id=317917
- put a quote from this at ~/notes/foucault_security_2007.md
- abstract for Paris:

> Techniques of the Predictor: generalizing complex populations

> A strikingly active policy-oriented apparatus has begun to emerge around certain forms of prediction associated with technology platforms. Unlike the predictive models that have long been part of the sciences, a set of institutions, procedures, calculations and operations have begin to take shape around problems of opacity, discrimination,  ownership and extension of predictive models in populations. In this paper, I will suggest that the governmentality of prediction currently taking shape can be understood from the perspective of what we might term 'techniques of the predictor' (after Crary's 'techniques of the observer').  Techniques of the predictor mobilise specific operational statements (classifications, identifications, rankings and recommendations), and generalize their production in new populations. The emerging governmentality of prediction might be see as part of the regularization of this mobilizing production.          

## Fri 30 Jun 2017 10:03:26 BST
- downloaded Royal Society report on governance ~/archive/data_governance/data-management-governance.pdf

## Mon 10 Jul 2017 16:31:59 BST

- I listened twice to that podcast from the google policy person -- its on the phone. 
- Conference sent me this briefing:

Thanks again for taking part in the conference in September in Paris. This message is to give you some background on the conference and its objectives, and provide some indications that may be useful to keep in mind when developing your talk.

The conference concludes our three-year comparative project on computation, prediction and policy, in which we looked at the evolution of the dominant modes of computation used in the area of energy policy-making, chemicals regulation and crime control. The heterogeneity of the policies we looked at meant that we considered quite diverse forms of computation/modelling, which had in common to help institutions predict or anticipate future issues, making policy more future-oriented – at least rhetorically.

The conference will also be comparative, with papers on modelling and computation in the area of security, transport, environment, energy, food and health. There will also be diversity in the practices, tools and cultures of modelling and computation that will be talked about, obviously, with some sectors discussing more established forms of statistical modelling, and others being on the more recent developments in terms of predictive analytics.

This is an occasion to develop a more general analysis of **how and why the practice of modelling and computation takes root in policy and governance**. To be sure, predicting or anticipating futures, is a key reason. But looking across policy areas, one finds that prediction/anticipation means quite a diversity of things (time horizons differ, ambition to change futures also varies…), and one may also find that it is not always the main reason, in fact. Simulating the effects of a decision to avert some contestations seem an important reason, for instance in energy policy-making. In crime control, the adoption of predictive analytics seem to be less about actually knowing future crime with accuracy, than about short-term optimization of patrolling tactics and control over police officers in the field.

In this context, it would be ideal if you could describe with as much clarity as possible, including for people that have little or no knowledge of the area you are investigating, **the particular modelling practice that you are considering, describing the data, tools, time-horizons, theories, etc., that characterizes it, putting them in the context of the history of the field, or positioning them vis-à-vis other ways of modelling and computing in the area.** But given that you are proposing a full framework, I think your paper will be strong on that anyway, and is pretty promising for our purpose.    

Second, it would be very beneficial for the discussion and accumulation of findings across the conference to keep in mind and try answering the question of **how and why has this or these particular way(s) of modelling/computing found its place in the policy area in question?** How and why did it or they become a recognized expertise, and something that gets concretely used by the policy-making bodies and administrations involved? That is the question of our project and of the conference, the one that is posed by the rise of predictive analytics (supposedly against more “traditional” forms of modelling and simulation), and the one on which we would like the conference to provide answers. So it would be great to have your take on that question.

We are not requesting to provide a full paper ahead of the conference. However, our plan is to provide participants and the audience with a compendium of short papers of between 1500 and 2000 words, summarizing your talk. It would be ideal if you could send me this by September 1st, so that it can be disseminated a few days before the event.

On another note, there will be a dinner for all speakers on Tuesday 12th, please mark it down in your agenda.
Don’t hesitate to write back if you have any question. I look forward to meeting you at the conference, and thanks again for taking part in it.

## Tue 11 Jul 2017 16:09:51 BST
- reading the Royal Society report.  and putting some excerpts in RoydalSocNotes.md
- TODO: get the Select Committee on Big Data report, as mentioned in the google policy podcast
- DONE: get this report The Royal Society. 2017 Machine learning: the power and promise of machines that learn by example. London: The Royal Society.
https://royalsociety.org/topics-policy/projects/machine-learning/ saved at ~/archive/data_governance/royal_soc_machine-learning-report_2017.pdf

## Wed 12 Jul 2017 16:45:07 BST
- making notes on the RoyalSoc ML things -- RoyalSoc_ML_2017.md

## Thu 20 Jul 2017 10:11:15 BST
- thinking on the bike ride home yesterday that the problem of  machine learning governance is its generalization. This makes it seem like specific governance should always be invoked; or that the problem is the context and the data governance. That's a problem. The point about  machine learning is that it has been constituted in an inter-disciplinary space, and its generalization has been part and parcel of its constitution. I should read against the grain of David Demortain's cfp?

## Sun 13 Aug 2017 17:06:11 AEST
- Listened to 'The Inquiry' on 'the Facebook algorithm' and how the NewsFeed was constructed around 2010. It might be a good example of to work with in this context.   
- could possibly put this together with some of the stuff from the RoyalSociety and see if it works; 
- could use Callon's idea of entanglement ... 

## Wed 30 Aug 2017 14:59:05 BST
- back at work after summer holidays;  How can I use what I've argued in the book about vectorisation, functions as partial observers, probabilisation, hyperobjects and diagrammatic thought to frame an argument?
- for 2000 words due 6 June
    - 31 Aug 750
    - 1 Sept 750
    - 4 Sept revise
    - 5 Sept enter revisions    
    - 6 Sept brief revise
- re-reading the cfp, and what the conference is about; it's really about prediction and its role in policy, not policy for governing prediction. 
- re-read my own abstract focused on techniques of the observer and its relation to populations; I see that it was focused on platforms; it would make sense to continue that idea, especially given the amount of work I've done on platforms recently ...  
- might make sense to use the framing from platform sociology to do that. 
- taking some notes on crary ~/notes/crary_techniques.md; could easily all-change 'vision' to 'prediction' in order to make an argument about governmentality as a response to a problem; 
    - can now exemplify this with the interplay between the subject of prediction and the predictive subject ... 

## Thu 31 Aug 2017 15:00:09 BST
- started actual paper in governing_prediction.rmd. Plan written. 
- TODO: look through the literature on governmentality for anything on policy. What is policy from the perspective of governmentality?
- TODO: look at Amoore's stuff on this -- very relevant!
- wrote 800 words on  machine learning; not sure how far I can get in describing any specific example, but maybe that doesn't matter. 

## Fri 01 Sep 2017 08:57:37 BST
- adding crary quotes 
- added some of the royal society report stuff
- got to about 1560 words -- want to make one simple point: the possibility of generalization in and of machine learning means a problem of governmentality that has to grapple with a population. But like all populations, a population of machine learners will pose problems of the unruly plurality, and a constant overstepping or impinging on the lines between person and thing, and indeed on the constitution of individual and group.

## Mon 04 Sep 2017 10:13:27 BST
- tweaking opening a bit -- what is my real point? That the autonomization of prediction means that models need to be governed? That is, the population of models in its unruly multiplicity becomes the object of governance?   
- plan for today -- write 700 words or so focusing on the problem of governance ...  
- here are the three main questions:
    1. how and why the practice of modelling and computation takes root in policy and governance
    2. how and why has this or these particular way(s) of modelling/computing found its place in the policy area in question?
    3. the particular modelling practice that you are considering, describing the data, tools, time-horizons, theories, etc., that characterizes it, putting them in the context of the history of the field, or positioning them vis-à-vis other ways of modelling and computing in the area.
- I can answer number 3 quite easily, but the first two, which are more or less the same, is harder. Maybe I can bracket the 2nd one, and focus on the first, giving it a spin that relates to the practices of data governance ... It'd be way easier if I was discussing an example like rental prices or job ads on Kaggle. But then I could do that -- look at all the Kaggle competitions that involve policy in some way (even some of the current ones do ...)    
- The point would be that the process of setting up competitions, opening up models to population constructors, and thereby affording their generalization -- this what energizes the field, and thereby changes the performativity of policy?        
- got into an example -- the TSA passenger screening algorithm -- mainly because I wanted to illustrate the point above.
- then restructured the argument around the example, putting in more data, and also moving things around a bit. 

## Tue 05 Sep 2017 10:30:47 BST
- 2 main parts of my argument about governance -- the impossibility of specificity; the reality of autonomisation/automation 
- today: write the section that deals with the 'learning'/automation bit. 
- did that mostly -- still needs an example of it in operation. But I'm doing the conclusion on the premise of restriction to specificity 

## Wed 06 Sep 2017 10:16:43 BST
- haven't developed the DHS example much around the actual models ... how can I do that given the models haven't been done yet?   
- looked at Brian Farrar -- he is actually implementing stuff to begin with; downloaded image from https://www.kaggle.com/jbfarrar/preprocessing-pipeline-and-convnet-trainer and also the Alexnet paper (which I should use for operative images) to ~/archive/data_intensive/machine_learning/imagenet-classification-with-deep-convolutional-nn.pdf 
- more less have a paper 4300 words (including quotes). governing_prediction.pdf

## Thu 07 Sep 2017 09:11:25 BST
- starting slides -- will just do 10 -- and editing paper quickly to send off.   
- did a version of the slides - adding as mackenzie_govern_predict.odp
- cleaned up the opening argument a bit, added a few references and sent governing_prediction.pdf
- TODO: if this was to develop -- add some of the lit on airport screening e.g. Lisa Parks on the impossibility of regulating the flow of objects Points of Departure: The Culture of US Airport Screening Lisa Parks Journal of Visual Culture, vol. 6, 2: pp. 183-200. , First Published Aug 1, 2007

## Fri 08 Sep 2017 10:53:40 BST
- going through text just once, quickly (< 1hour) to highlight main argument 
- adding more images. Just realised I need to force that. 
