library(ggplot2)
xlim = range(SAheart$sbp)
ylim = range(SAheart$ldl)
ytmp = seq(ylim[1], ylim[2], len=75)
xtmp = seq(xlim[1], xlim[2], len=75)
newx = expand.grid(xtmp, ytmp)
SAheart_model2 = glmnet(y=SAheart[,'chd'], x = as.matrix(SAheart[, c('sbp', 'ldl')]), family='binomial')
yhat = predict(SAheart_model2, as.matrix(newx), type="class", s=0.001)
df = data.frame(x=rep(xtmp, length(ytmp)), y=rep(ytmp, each=length(xtmp)), z=as.numeric(as.vector(yhat)))
g=ggplot(data=SAheart, aes(x=sbp, y = ldl)) + geom_point(aes(color=chd, shape=chd))
g+geom_contour(data=df, aes(x=x,y=y, z=z), breaks=c(0,0.5))
#plot(SAheart$sbp, SAheart$ldl, shape=SAheart$chd)
#contour(xtmp,ytmp, matrix(as.numeric(yhat),75,75), levels=c(1,2), add=TRUE, drawlabels=FALSE)
