# ch1_notes.rmd

How to write about data and models
Making models of data
Associating with data: a praxiography of machine learning

## from proposal

This chapter is primary a methodological discussion that addresses several different problems in working with machine learning. These problems range from quite philosophical issues through to quite practical ones. At the philosophical end, it draws on various pieces of recent and not-so-recent theoretical work (for instance, the anthropologist Paul Rabinow's work on the concept of 'equipment' [@rabinow_anthropos_2003]; the philosopher A.N. Whitehead on the spatial dimensionality of thought [@whitehead_modes_1958]; the philosopher Anne-Marie Mols' work praxiography -- writing about practices [@mol_body_2003])  to discuss how we might think about working on highly technical or scientific areas such as machine learning in ways that allow consideration of their more general situation.  It also draws on some cultural and psychoanalytic accounts of architecture and objects [@bollas_evocative_2009; @wilson_affect_2010] to suggest how the researcher him or herself relate to objects of research.  Finally in this vein, the chapter poses the methodological problem of working with large bodies of scientific and technical literature, and illustrates this by describing the growth of machine learning techniques in science and engineering research since the early 1960s, focusing on the growth of key techniques and algorithms [@kelty_ten_2009].

With these questions about thinking, techniques, subjectivity and literature on the table, the chapter then presents a series of vignettes that display some of the ways in which research and writing critical accounts of data cultures and data economies can make use of the tools, techniques, instruments and services of 'data science' to generate textual, diagrammatic and modelised accounts of contemporary culture.  A standard teaching example -- house-price prediction -- links these vignettes, but the real focus here is on two foundational issues: how machine learning treats data as a dimensional material that it seeks to reshape or recase  in different dimensions ('models'); how implementing machine learning techniques shifts our relation to them.  

Woven throughout this discussion of a praxiography of data, [TBC] Via a discussion of the development of `R`, the chapter analyses the  transverse, cross-disciplinary implementation of machine learning techniques in recent decades. It describes some of the transformations in software, network and scientific cultures that underpin the recent growth in data techniques and methods. These range across transformations in statistical science associated with greater computational capacity; the mutations in network,  database and digital device architectures and infrastructures that yield much greater abundance of data in various forms; and the intermeshing of knowledge economies with the media, communication, transaction, transport and logistics systems. It will trace how the lateral associations and multivalencies of data have developed through key software artefacts such as the widely used `R` programming language, and in generic programming languages such as Python. Coming from  the author's own history of working with machine learning or online accounts of machine learning,  well as the ecology of thousands of software packages  associated with the statistical programming language `R`.


## Overview

- reconstruction vs problematization -- Rabinow -- on equipment
- data: its giveness, abstraction and actuality
    - observant participation -- developing Wacquant; participating by observing
    - writing recursively -- developing Kelty w.r.t subjects
    - James on feeling of transition - and practicing radical empiricism - -see Massumi
- Implementing machine learning
    - the case of `R` -- the scientific
    - the case of Python -- the business/industry
    - the case of javascript -- popular culture
- convergence and learning: for fitting a line; but then for choosing which features to use to learn
- learning about learning --
    - the Literature - landecker and kelty on treating literature as the informant; examples such as Cover-Hart, Breiman, etc
- things to include:
    - my `R` books, libraries, papers, competitions, blogs, talking, courses
    - `knitr`/`ipython` notebooks - executable - some examples from python notebooks
    - the notion of repl -- read-evaluate-print-loop
    - Add in Animation and Automation – The Liveliness and Labours of Bodies and Machines Body & Society March 2012 18: 1-46, 
    - machine learning textbooks -- hastie, williams, manning, see document archive
    - the github version of the book
    -

## Todo
- comment on the typography of the maths -- the use of bold, italics, of German capitals, greek letters, upper and lower case, brackets, 

- add Foucault on the appearance of deep order in life/language/labour -- this is a really important thread to draw through - in this case through the reconstruction of the _table_. 
- add quotes from Foucault on the table of space of order, and ask how he thought about quantity, etc; and what is happening to tables today.
- done Bogost on carpentering, and the problems of writing -- I have a take on that ... 'source code itself often offers inroads in alien phenomenology -- particular when carpentered to reveal the internal experience of withdrawn units 105'
- Landecker & Kelty on the literature as informant;  -- very important to do more on this
- Cathy O'Neill writing about why big data is over -- doing one course is not enough ... 
- done? On the aridness of the textbooks and literature and what to do about that. 
- done - Domingos on feature engineering and why it is important -- article in ACM
-  add the recent books like ML in Python, Thoughtful ML, etc
- add Parisi quote about software cultures: '
>The epochal challenge of programming cultures is to venture into the infinity of incomputable probabilities (infinite discrete unities that are bigger than the totality of the whole sequence of algorithmic instructions) that lies beyond both the digital ground and interactive empiricism. 77

- the entwining of the models and the data with this text -- it can't be shown in this text, in the same way that it can't be easily shown in the world.  
- complain about all the vignettes and case studies in this area - Mayer-Schonberger, the podcasts, etcs
