#  Acknowledgments 
\label{ch:acknowledgments}

```{r global_options0, include=FALSE}
knitr::opts_chunk$set(fig.width=12, tidy=TRUE, fig.height=8, 
                      echo=FALSE,  fig.show='hide', results='hide', warning=FALSE, message=FALSE, dev='pdf')
library(RSQLite)
con <- dbConnect(RSQLite::SQLite(),'../ml_lit/all_refs.sqlite3')
library(ggplot2)
library(stringr)
library(xtable)
options(xtable.comment = FALSE)
options(xtable.comment = FALSE)
options(xtable.size = 'tiny')
options(xtable.tableplacement = '!htbp')
options(xtable.rownames = FALSE)
simpleCap <- function(x) {
    s <- strsplit(x, " |-")[[1]]
    return (paste(toupper(substring(s, 1,1)), tolower(substring(s, 2)), sep="", collapse=" "))
  }
```

From 2007-2012, I benefited greatly from a research position in the UK Economic and Social Research Council-funded Centre for Economic and Social Aspects of Genomics at Lancaster University. Certain colleagues there, initially in the 'Sociomics Core Facility', participated in the inception of this  book. Ruth McNally with her almost geeky interest in genomics, Paul Oldham with his enthusiasm for 'all the data,' Maureen McNeil with her critical acuity, and Brian Wynne with his connective thought were participants in many discussions concerning the transformation of life sciences around which my interest in machine learning first crystallised.

The Technology in Practice Group at ITU Copenhagen hosted some of the research work during 2014. Brit Ross Winthereik in particular made it possible for to develop some of the key ideas. I was lucky too to be  part of an excellent research team on 'Socialising Big Data'(2013-2015)  that included Penny Harvey, Celia Lury, Ruth McNally and Evelyn Ruppert. We had excellent  discussions.

My colleagues in the science studies at Lancaster, especially Maggie Mort, Lucy Suchman, and Claire Waterton are always a delight to work with.  I have also been  fortunate to have worked with inspiring and adventurous doctoral students at Lancaster during the writing of this book. Lara Houston, Mette Kragh Furbo, Felipe Raglianti, Emils Kilis, Xaroula Charalampia, and Nina Ellis have all helped and provided inspiration in different ways. Sjoerd Bollebakker very kindly updated many of the scientific literature searches towards the end of the book's writing. 

Various academic staff in the Department of Applied Mathematics and Statistics at Lancaster University shepherded me through post-graduate statistics training courses: Brian Francis for his course of 'Data Mining,' David Lucy for his course on 'Bayesian Statistics', Thomas Jakl for his course 'Genomic Data Analysis' and TBA's course on 'Missing Data.'  Since 2015, I've also come to know some machine learners much better through the Data Science Institute, Lancaster University.

My friends in the _Computational Cultures_ editorial group have listened to and irrationally encouraged various threads of work runnning the book. I warmly acknowledge the existence of Matthew Fuller, Andrew Goffey, Graham Harwood and Olga Goriunova. Nina Wakeford at once point encouraged me to be naïve.  

Far away in Australia, Anna Munster has stayed in touch.  As always, Celia Roberts helped me sort out what I really want to do. 

