# Introduction


## overview



## to do
- bring in materials from warwick talk
- recursiveness of this text
- the role of industry -- machine learning as industrial
- make the distinction between supervised and unsupervised
- the form of writing; finding oneself experimenting with code
- trying to find experiments and experiences
-  the ml literature -- how the terms takes shape -- use ipython notebooks for that. machine learning as very loose assemblage; how it coalesces; etc. 
-  I can't cover all the algorithms, techniques, settings

## quotes to use
it follows that if one's object is an anthropological account of a problematization, then one's informants will differ from each other. The challenge lies in finding an experiential and experimental site that would provide a contemporary instance. 87 Rabinow

What I am attempting to do is to reflect on how it might be possible to transfigure elements of the equipment of modern method into a  form of modern meditation, and to bring the benefits and effects of that transformation to bear on enquiry. Rabinow 12 -  used this already in ch2 intro

source code itself often offers inroads in alien phenomenology -- particular when carpentered to reveal the internal experience of withdrawn units, Bogost

the challenge, which I deem a materialist challenge, is that whatever the mess and perplexity that may result, we should resist the temptation to pick and choose among practices Stengers, wondering, 2011, 379

"The sheer density of the collisions of classification schemes in our lives calls for a new kind of science, a new set of metaphors, linking traditional social science and computer and information science. We need a topography of things such as the distribution of ambiguity.  ...  It will also use the best of object-oriented programming and other areas of computer science to describe this territory" [@bowker_sorting_1999, 31].


Quotes from Lanier

# examples to use
- [@le_building_2011] -- paper on the cat videos 
